#                                          KNN ALGORITHM


* It stands for k nearest neighbour alogorithm
* it is a supervised learning alogorithm 
* it has 1).REGRESSION: TRYing to predict the numerical data 
* 2). classification: tryting to predict the categorical data
* it is one of the simplest ML
* it assumes the similarities between the new cases or the data and available cases and put the new available cases into the 
* to the categorical data that is more similar to the available category

* it is also calle lazy learner algorithm bcz it doesnot learn from trainset immediately instaed  it stores the dataset 
* at the time of classification it performs action 

*  knn is a non parametric it doesnot make any assumptions on underlining dataset 



# why do we need a knn algorithm

* if we have 2 categorical block of data and one new datapoint is there to assign this new datapoint we use knn 

# how does knn works

* step:1
* firstly it selects the no of k of neighbours.
* step 2:
* calculate the euclidean distance of k neighbors.
* step 3:
* it takes the knn as per the euclidean distance 
* step 4:
* among these knn count the no of datapoints on each category
* step 5:
* assign a new datapoints to the category for which the no of neighbors are max 
* step 6:
*  our model is ready

# how to choose k value in knn

* by default it takes k=5 always preferres'
* k=1 or k=2 can be noisy and leads to the effects of out;iers in the model
* for larger values k is good execution process can be difficult
* 

# ADVANTAGES:



* IT IS simple to implement
* it is robust to noisy training dataset
* it can be more effective if the tarining data is large 

# DIS_ADV


* the computational cost is high bcz of calculating the distance between all the tarining points for large samples
* always determine value of k 

# how to implement the knn algorithm


* data pre_processing step
* fitting the knn to the tarining dataset
* predicting the testing results
* test accuracy of results
* visualizing the test results

In [1]:
import numpy as np
import pandas as pd
import os
import glob
import matplotlib.pyplot as plt
import seaborn as sbn

In [51]:
x=pd.read_excel(r"C:\Users\harid\OneDrive\Desktop\python\data\datasets\Product_sales_v1.xlsx")

In [52]:
x.shape

(467, 2)

In [53]:
x.columns

Index(['Age', 'Bought'], dtype='object')

In [54]:
# extarcting the independent and dependent variables

a=x.iloc[:,[0,1]]
b=x.iloc[:,1]

In [55]:
a

Age  Bought
0      1       0
1      1       0
2      1       0
3      1       0
4      1       0
..   ...     ...
462   43       0
463   60       1
464   63       1
465   50       0
466   61       1

[467 rows x 2 columns]

In [56]:
b

0      0
1      0
2      0
3      0
4      0
      ..
462    0
463    1
464    1
465    0
466    1
Name: Bought, Length: 467, dtype: int64

In [57]:
# splitting the data into train test 

from sklearn.model_selection import train_test_split
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.25,random_state=42)

In [58]:
len(a_train)

350

In [59]:
len(a_test)

117

In [60]:
# feature scaling

from sklearn.preprocessing import StandardScaler

In [61]:
st=StandardScaler()
a_train=st.fit_transform(a_train)
a_test=st.fit_transform(a_test)

In [19]:
a_train

array([[-1.11766834e+00,  1.09621860e+00],
       [ 1.31767413e+00, -1.23265840e+00],
       [ 3.35844609e-02, -1.55210567e-01],
       [ 1.60548733e+00, -1.56560745e+00],
       [-8.96273573e-01,  7.71217942e-01],
       [-1.06944931e-02, -1.26066486e-01],
       [-1.20622625e+00,  1.21986016e+00],
       [ 1.25125570e+00, -1.06927492e+00],
       [ 1.42837151e+00, -1.34658526e+00],
       [-1.44976050e+00,  1.58725220e+00],
       [ 5.57239378e-02, -1.91419880e-01],
       [-1.87810309e-01,  1.41529165e-01],
       [ 1.02986093e+00, -8.76747356e-01],
       [-1.09552887e+00,  1.04411252e+00],
       [ 2.10700277e-01, -2.70020582e-01],
       [ 1.11841883e+00, -9.68595368e-01],
       [-7.85576188e-01,  6.19315460e-01],
       [-1.60473684e+00,  1.76476615e+00],
       [-9.84831481e-01,  9.25769885e-01],
       [-3.64926125e-01,  3.01380032e-01],
       [ 1.64976628e+00, -1.62654507e+00],
       [-2.32089263e-01,  2.29844561e-01],
       [-1.33906311e+00,  1.33996909e+00],
       [ 1.

In [62]:
a_test

array([[-1.05357059, -0.9258201 ],
       [-1.01040961, -0.9258201 ],
       [-1.13989256, -0.9258201 ],
       [ 0.58654665, -0.9258201 ],
       [-1.01040961, -0.9258201 ],
       [-0.49247785, -0.9258201 ],
       [-0.53563883, -0.9258201 ],
       [-1.22621452, -0.9258201 ],
       [-0.66512177, -0.9258201 ],
       [ 1.06131744,  1.08012345],
       [-0.96724863, -0.9258201 ],
       [-1.01040961, -0.9258201 ],
       [ 1.44976626,  1.08012345],
       [-0.96724863, -0.9258201 ],
       [ 1.23396136,  1.08012345],
       [ 0.50022469,  1.08012345],
       [ 1.44976626,  1.08012345],
       [ 0.62970763,  1.08012345],
       [ 0.54338567,  1.08012345],
       [-0.96724863, -0.9258201 ],
       [-1.22621452, -0.9258201 ],
       [-0.92408765, -0.9258201 ],
       [-1.22621452, -0.9258201 ],
       [ 1.01815646,  1.08012345],
       [-0.96724863, -0.9258201 ],
       [-0.57879981, -0.9258201 ],
       [ 0.45706371,  1.08012345],
       [ 1.23396136,  1.08012345],
       [-1.13989256,

In [63]:
# knn fitting

from sklearn.neighbors import KNeighborsClassifier

In [64]:
classifier=KNeighborsClassifier(n_neighbors=5,p=2)
classifier.fit(a_train,b_train)
classifier.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [65]:
y_predict=classifier.predict(a_test)

In [66]:
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0], dtype=int64)

In [69]:
list(pd.crosstab(b_test,y_predict))

[0, 1]

In [68]:
from sklearn.metrics import confusion_matrix
confusion_matrix(b_test,y_predict)

array([[63,  0],
       [ 0, 54]], dtype=int64)

In [ ]:
# visualization



# real world appications for knn alo]gorithm

* understand the credit racing
* currency exchange rate
* bank rup
* trading
* credit rating
* bank customer profiling


# knn we used to treat the missing value for that purpose